class_name Patient
## Holds information on the AI patient.
##
## Facilitates access to patient information.

var info: Array				## Holds general patient health and background info
var history: Array[Array]			## Holds patient history
var immunizations: Array[Array]		## Holds patient immunizations
var medications: Array[Array]		## Holds patient medications


func _init():
	info = []
	history = []
	medications = []
	immunizations = []


## Add general health and background info
func set_info(value) -> void:
	info = value


## Add history info
func add_history(hist) -> void:
	history.append(hist)


## Add immunization info
func add_immunization(immun) -> void:
	immunizations.append(immun)


## Add medication info
func add_medication(med) -> void:
	medications.append(med)


## Convert a patient parameter to its respective index in the array
func to_index(field) -> int:
	var conversions = {
		"Patient First Name": 0,
		"Patient Last Name": 1,
		"Attending Physician First Name": 2,
		"Attending Physician Last Name": 3,
		"Accuracy (What signs/symptoms/columns in this sheet does the patient have accurate knowledge about?)" :4,
		"Birthday (YYYY-MM-DD)": 5,
		"Age": 6,
		"Sex": 7,
		"Address": 8,
		"Parent/ Guardian First Name": 9,
		"Parent/ Guardian Last Name": 10,
		"Informant First Name": 11,
		"Informant Last Name": 12,
		"Reliability": 13,
		"Dwelling Type (House, Apt.)": 14,
		"Number Of Rooms": 15,
		"Appliances (Radio, Tv, Refrigerator) *Can Be Multiple": 16,
		"Number Of Household Members": 17,
		"Transportation (None, Car, Jeep, Motorcycle)": 18,
		"Landline Number (11 Digits)": 19,
		"Phone Number (12 Digits Starting With 63)": 20,
		"Nationality": 21,
		"Language": 22,
		"Religion": 23,
		"Annual Family Income": 24,
		"Chief Complaint": 25,
		"Concerns Regarding Problem": 26,
		"History Of Present Illness": 27,
		"Provocation": 28,
		"Quality": 29,
		"Region": 30,
		"Severity": 31,
		"Timing": 32,
		"Stakeholder": 33,
		"Stakeholder's Interest In Issue": 34,
		"Stakeholder's Role": 35,
		"Stakeholder's Level Of Influence": 36,
		"Pertinent Beliefs": 37,
		"Impact On Family": 38,
		"Facilitating": 39,
		"Hindering": 40,
		"Burden Of Illness": 41,
		"Pertinent Legislation Or Policies": 42,
		"Breastfed Till": 43,
		"Formula": 44,
		"Weaning Age": 45,
		"Current Diet": 46,
		"Food Allergy": 47,
		"Term": 48,
		"Delivered Via": 49,
		"To A (Age)": 50,
		"G": 51,
		"P": 52,
		"BW": 53,
		"Attended By First Name": 54,
		"Attended By Last Name": 55,
		"Perinatal CX": 56,
		"Gross Motor": 57,
		"Adaptive-Fine Motor": 58,
		"Speech": 59,
		"Personal And Social": 60,
		"Fever": 61,
		"Weight Gain": 62,
		"Weight Loss": 63,
		"Weakness": 64,
		"Fatigue": 65,
		"Other General Symptoms": 66,
		"Rashes": 67,
		"Lumps": 68,
		"Sores": 69,
		"Itching": 70,
		"Muscle Pains": 71,
		"Joint Pains": 72,
		"Changes in Skin Color": 73,
		"Joint Swelling": 74,
		"Changes in Hair/Nails": 75,
		"Gout": 76,
		"Other Musculoskeletal or Dermatologic Symptoms": 77,
		"Headache": 78,
		"Dizziness": 79,
		"Blurring of Vision": 80,
		"Tinnitus": 81,
		"Deafness": 82,
		"Nosebleeds": 83,
		"Frequent Colds": 84,
		"Hoarseness": 85,
		"Dry Mouth": 86,
		"Gum Bleeding": 87,
		"Enlarged Lymph Nodes": 88,
		"Other HEENT Symptoms": 89,
		"Dyspnea": 90,
		"Hemoptysis": 91,
		"Cough": 92,
		"Wheezing": 93,
		"Other Respiratory Symptoms": 94,
		"Palpitations": 95,
		"Chest Pains": 96,
		"Syncope": 97,
		"Orthopnea": 98,
		"Other Cardiovascular Symptoms": 99,
		"Nausea": 100,
		"Vomiting": 101,
		"Dysphagia": 102,
		"Heartburn": 103,
		"Change in Bowel Habits": 104,
		"Rectal Bleeding": 105,
		"Jaundice": 106,
		"Other Gastrointestinal Symptoms": 107,
		"Nocturia": 108,
		"Dysuria": 109,
		"Urinary Frequency": 110,
		"Hematuria": 111,
		"Other Genitourinary Symptoms": 112,
		"Excessive Sweating": 113,
		"Heat Intolerance": 114,
		"Polyuria": 115,
		"Excessive Thirst": 116,
		"Cold Intolerance": 117,
		"Other Endocrine Symptoms": 118,
		"History of Tuberculosis": 119,
		"History of Asthma": 120,
		"History of Diabetes": 121,
		"History of Hypertension": 122,
		"History of Psychiatric Consult": 123,
		"History of Cancer": 124,
		"Prior Surgeries/Hospitalizations": 125,
		"History of Allergies": 126,
		"Cancer Site in History": 127,
		"Prior Surgeries Or Hospitalization Dates": 128,
		"Prior Surgeries Or Hospitalization Reasons": 129,
		"Allergies in History": 130,
		"Other Past Medical History": 131,
		"Family History of Tuberculosis": 132,
		"Family History of Asthma": 133,
		"Family History of Psychiatric Consult": 134,
		"Family History of Diabetes": 135,
		"Family History of Cardiovascular Disease": 136,
		"Family History of Cancer": 137,
		"Family History of Allergies": 138,
		"Cancer Site in Family History": 139,
		"Relationship To Cancer Patient": 140,
		"Allergies In Family History": 141,
		"Other Family History": 142,
		"Genogram (Describe Through Text)": 143,
		"Social And Environmental History": 144,
		"Last Menstrual Period (YYYY-MM-DD)": 145,
		"Previous Menstrual Period (YYYY-MM-DD)": 146,
		"Duration Of Menses": 147,
		"Interval Of Menses": 148,
		"Volume Of Menses": 149,
		"Menarche": 150,
		"Coitarche": 151,
		"DPT/Polio Immunization": 152,
		"HIB Immunization": 153,
		"Hepatitis B Immunization": 154,
		"MMR Immunization": 155,
		"Measles Immunization": 156,
		"Varicella Immunization": 157,
		"Pneumococcal Immunization": 158,
		"Influenza Immunization": 159,
		"Hepatitis A Immunization": 160,
		"DPT/Polio Doses": 161,
		"HIB Doses": 162,
		"Hepatitis B Doses": 163,
		"MMR Doses": 164,
		"Measles Doses": 165,
		"Varicella Doses": 166,
		"Pneumococcal Doses": 167,
		"Influenza Doses": 168,
		"Hepatitis A Doses": 169,
		"Other Immunizations": 170,
		"Home": 171,
		"Education": 172,
		"Activities": 173,
		"Drugs": 174,
		"Sexual Activity": 175,
		"Suicide/Depression": 176,
		"Family": 177,
		"Source Of Income And Dynamics": 178,
		"General Appearance": 179,
		"General Behavior": 180,
		"Attitude Towards Examiner": 181,
		"Mood": 182,
		"Affect": 183,
		"Speech2": 184,
		"Perceptual Disturbance": 185,
		"Stream of Thought": 186,
		"Thought Content": 187,
		"Impulse Control": 188,
		"Intellectual Capacity Global Estimate": 189,
		"Consciousness": 190,
		"Other State of Consciousness": 191,
		"Attention Span": 192,
		"Attention Span Notes": 193,
		"Orientation Time": 194,
		"Orientation Place": 195,
		"Orientation Person": 196,
		"Memory": 197,
		"Memory Notes": 198,
		"Calculation": 199,
		"Calculation Notes": 200,
		"Fund of Information": 201,
		"Fund of Information Notes": 202,
		"Insight": 203,
		"Insight Notes": 204,
		"Judgment": 205,
		"Planning": 206,
		"Planning Notes": 207,
		"Speech Quality": 208,
		"Speech Disorder Others": 209,
		"Other High Cortical Functions": 210,
		"Glasgow Coma Scale GCS": 211,
		"Glasgow Coma Scale E": 212,
		"Glasgow Coma Scale V": 213,
		"Glasgow Coma Scale M": 214,
		"Medications": 215,
		"Additional Details Regarding History": 216,
		"Additional Details Regarding Context Including Ethical Considerations": 217,
		"Informant": 218
	}

	return conversions.get(field, -1)


func to_field(index) -> String:
	var conversions = {
		0: "Patient First Name",
		1: "Patient Last Name",
		2: "Attending Physician First Name",
		3: "Attending Physician Last Name",
		4: "Accuracy (What signs/symptoms/columns in this sheet does the patient have accurate knowledge about?)",
		5: "Birthday (YYYY-MM-DD)",
		6: "Age",
		7: "Sex",
		8: "Address",
		9: "Parent/ Guardian First Name",
		10: "Parent/ Guardian Last Name",
		11: "Informant First Name",
		12: "Informant Last Name",
		13: "Reliability",
		14: "Dwelling Type (House, Apt.)",
		15: "Number Of Rooms",
		16: "Appliances (Radio, Tv, Refrigerator) *Can Be Multiple",
		17: "Number Of Household Members",
		18: "Transportation (None, Car, Jeep, Motorcycle)",
		19: "Landline Number (11 Digits)",
		20: "Phone Number (12 Digits Starting With 63)",
		21: "Nationality",
		22: "Language",
		23: "Religion",
		24: "Annual Family Income",
		25: "Chief Complaint",
		26: "Concerns Regarding Problem",
		27: "History Of Present Illness",
		28: "Provocation",
		29: "Quality",
		30: "Region",
		31: "Severity",
		32: "Timing",
		33: "Stakeholder",
		34: "Stakeholder's Interest In Issue",
		35: "Stakeholder's Role",
		36: "Stakeholder's Level Of Influence",
		37: "Pertinent Beliefs",
		38: "Impact On Family",
		39: "Facilitating",
		40: "Hindering",
		41: "Burden Of Illness",
		42: "Pertinent Legislation Or Policies",
		43: "Breastfed Till",
		44: "Formula",
		45: "Weaning Age",
		46: "Current Diet",
		47: "Food Allergy",
		48: "Term",
		49: "Delivered Via",
		50: "To A (Age)",
		51: "G",
		52: "P",
		53: "BW",
		54: "Attended By First Name",
		55: "Attended By Last Name",
		56: "Perinatal CX",
		57: "Gross Motor",
		58: "Adaptive-Fine Motor",
		59: "Speech",
		60: "Personal And Social",
		61: "Fever",
		62: "Weight Gain",
		63: "Weight Loss",
		64: "Weakness",
		65: "Fatigue",
		66: "Other General Symptoms",
		67: "Rashes",
		68: "Lumps",
		69: "Sores",
		70: "Itching",
		71: "Muscle Pains",
		72: "Joint Pains",
		73: "Changes in Skin Color",
		74: "Joint Swelling",
		75: "Changes in Hair/Nails",
		76: "Gout",
		77: "Other Musculoskeletal or Dermatologic Symptoms",
		78: "Headache",
		79: "Dizziness",
		80: "Blurring of Vision",
		81: "Tinnitus",
		82: "Deafness",
		83: "Nosebleeds",
		84: "Frequent Colds",
		85: "Hoarseness",
		86: "Dry Mouth",
		87: "Gum Bleeding",
		88: "Enlarged Lymph Nodes",
		89: "Other HEENT Symptoms",
		90: "Dyspnea",
		91: "Hemoptysis",
		92: "Cough",
		93: "Wheezing",
		94: "Other Respiratory Symptoms",
		95: "Palpitations",
		96: "Chest Pains",
		97: "Syncope",
		98: "Orthopnea",
		99: "Other Cardiovascular Symptoms",
		100: "Nausea",
		101: "Vomiting",
		102: "Dysphagia",
		103: "Heartburn",
		104: "Change in Bowel Habits",
		105: "Rectal Bleeding",
		106: "Jaundice",
		107: "Other Gastrointestinal Symptoms",
		108: "Nocturia",
		109: "Dysuria",
		110: "Urinary Frequency",
		111: "Hematuria",
		112: "Other Genitourinary Symptoms",
		113: "Excessive Sweating",
		114: "Heat Intolerance",
		115: "Polyuria",
		116: "Excessive Thirst",
		117: "Cold Intolerance",
		118: "Other Endocrine Symptoms",
		119: "History of Tuberculosis",
		120: "History of Asthma",
		121: "History of Diabetes",
		122: "History of Hypertension",
		123: "History of Psychiatric Consult",
		124: "History of Cancer",
		125: "Prior Surgeries/Hospitalizations",
		126: "History of Allergies",
		127: "Cancer Site in History",
		128: "Prior Surgeries Or Hospitalization Dates",
		129: "Prior Surgeries Or Hospitalization Reasons",
		130: "Allergies in History",
		131: "Other Past Medical History",
		132: "Family History of Tuberculosis",
		133: "Family History of Asthma",
		134: "Family History of Psychiatric Consult",
		135: "Family History of Diabetes",
		136: "Family History of Cardiovascular Disease",
		137: "Family History of Cancer",
		138: "Family History of Allergies",
		139: "Cancer Site in Family History",
		140: "Relationship To Cancer Patient",
		141: "Allergies In Family History",
		142: "Other Family History",
		143: "Genogram (Describe Through Text)",
		144: "Social And Environmental History",
		145: "Last Menstrual Period (YYYY-MM-DD)",
		146: "Previous Menstrual Period (YYYY-MM-DD)",
		147: "Duration Of Menses",
		148: "Interval Of Menses",
		149: "Volume Of Menses",
		150: "Menarche",
		151: "Coitarche",
		152: "DPT/Polio Immunization",
		153: "HIB Immunization",
		154: "Hepatitis B Immunization",
		155: "MMR Immunization",
		156: "Measles Immunization",
		157: "Varicella Immunization",
		158: "Pneumococcal Immunization",
		159: "Influenza Immunization",
		160: "Hepatitis A Immunization",
		161: "DPT/Polio Doses",
		162: "HIB Doses",
		163: "Hepatitis B Doses",
		164: "MMR Doses",
		165: "Measles Doses",
		166: "Varicella Doses",
		167: "Pneumococcal Doses",
		168: "Influenza Doses",
		169: "Hepatitis A Doses",
		170: "Other Immunizations",
		171: "Home",
		172: "Education",
		173: "Activities",
		174: "Drugs",
		175: "Sexual Activity",
		176: "Suicide/Depression",
		177: "Family",
		178: "Source Of Income And Dynamics",
		179: "General Appearance",
		180: "General Behavior",
		181: "Attitude Towards Examiner",
		182: "Mood",
		183: "Affect",
		184: "Speech2",
		185: "Perceptual Disturbance",
		186: "Stream of Thought",
		187: "Thought Content",
		188: "Impulse Control",
		189: "Intellectual Capacity Global Estimate",
		190: "Consciousness",
		191: "Other State of Consciousness",
		192: "Attention Span",
		193: "Attention Span Notes",
		194: "Orientation Time",
		195: "Orientation Place",
		196: "Orientation Person",
		197: "Memory",
		198: "Memory Notes",
		199: "Calculation",
		200: "Calculation Notes",
		201: "Fund of Information",
		202: "Fund of Information Notes",
		203: "Insight",
		204: "Insight Notes",
		205: "Judgment",
		206: "Planning",
		207: "Planning Notes",
		208: "Speech Quality",
		209: "Speech Disorder Others",
		210: "Other High Cortical Functions",
		211: "Glasgow Coma Scale GCS",
		212: "Glasgow Coma Scale E",
		213: "Glasgow Coma Scale V",
		214: "Glasgow Coma Scale M",
		215: "Medications",
		216: "Additional Details Regarding History",
		217: "Additional Details Regarding Context Including Ethical Considerations",
		218: "Informant"
	}

	return conversions.get(index, "")